# Generated by Django 5.0.6 on 2024-06-09 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=100)),
                ('total_contract_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property_type', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('lot_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location_coordinates', models.CharField(max_length=100)),
                ('contact_agent', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='house_images/')),
                ('house_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbrs_app.houselisting')),
            ],
        ),
    ]
