# Generated by Django 5.0.6 on 2024-06-09 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbrs_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houselisting',
            name='house_images',
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='house_images/')),
                ('house_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbrs_app.houselisting')),
            ],
        ),
        migrations.AddField(
            model_name='houselisting',
            name='house_images',
            field=models.ManyToManyField(related_name='house_images', to='pbrs_app.imagemodel'),
        ),
    ]
