# Generated by Django 5.0.6 on 2024-06-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbrs_app', '0002_remove_houselisting_house_images_imagemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houselisting',
            name='house_images',
            field=models.ManyToManyField(to='pbrs_app.imagemodel'),
        ),
    ]
