# Generated by Django 5.0.6 on 2024-06-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbrs_app', '0002_houselisting_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houselisting',
            name='description',
            field=models.TextField(default='', null=True),
        ),
    ]
