# Generated by Django 5.0.6 on 2024-07-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbrs_app', '0003_alter_houselisting_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houselisting',
            name='location_coordinates',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
