# Generated by Django 5.0.6 on 2024-06-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbrs_app', '0003_alter_houselisting_house_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houselisting',
            name='house_images',
        ),
    ]
