# Generated by Django 5.0.6 on 2024-07-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbrs_app', '0004_alter_houselisting_location_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houselisting',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='location_coordinates',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
