# Generated by Django 5.0.6 on 2024-07-03 15:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbrs_app', '0005_alter_houselisting_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='houselisting',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='houselisting',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
