# Generated by Django 5.0.6 on 2024-07-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbrs_app', '0006_houselisting_created_houselisting_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houselisting',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='houselisting',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
