# Generated by Django 5.0.6 on 2024-07-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbrs_app', '0007_alter_houselisting_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='houselisting',
            name='financing',
            field=models.CharField(default='', max_length=64),
        ),
    ]
